"""Typed models for data exchanged with the LangGraph agent API.

These mirror the Pydantic schemas the backend exposes in `app/schemas`, so the
frontend validates responses instead of passing raw dictionaries around.
"""

from datetime import datetime
from typing import (
    List,
    Literal,
)

from pydantic import (
    BaseModel,
    Field,
)

MAX_MESSAGE_LENGTH = 3000


class Token(BaseModel):
    """A JWT issued by the API for either a user or a chat session.

    Attributes:
        access_token: The bearer token value.
        token_type: The token type, always "bearer".
        expires_at: When the token stops being accepted.
    """

    access_token: str
    token_type: str = "bearer"
    expires_at: datetime


class UserAccount(BaseModel):
    """An authenticated user together with its user-scoped token.

    Attributes:
        id: The user's numeric identifier.
        email: The user's email address.
        username: Optional display name.
        token: The user-scoped token used for session management calls.
    """

    id: int | None = None
    email: str = ""
    username: str | None = None
    token: Token


class ChatSession(BaseModel):
    """A chat session and the session-scoped token that unlocks it.

    Attributes:
        session_id: The session's unique identifier.
        name: Display name, auto-generated by the backend after the first message.
        token: The session-scoped token required by the chatbot endpoints.
    """

    session_id: str
    name: str = ""
    token: Token

    @property
    def display_name(self) -> str:
        """Return a human-friendly label for the session.

        Returns:
            str: The session name, or a placeholder when it has not been named yet.
        """
        return self.name.strip() or "New chat"


class ChatMessage(BaseModel):
    """A single turn in a conversation.

    Attributes:
        role: Who produced the message.
        content: The message text.
    """

    role: Literal["user", "assistant", "system"]
    content: str = Field(..., min_length=1, max_length=MAX_MESSAGE_LENGTH)


class HealthStatus(BaseModel):
    """The API's self-reported health.

    Attributes:
        status: Overall status string, e.g. "healthy" or "degraded".
        version: The API version.
        environment: The environment the API is running in.
        components: Per-component health flags.
    """

    status: str = "unknown"
    version: str = ""
    environment: str = ""
    components: dict[str, str] = Field(default_factory=dict)


__all__: List[str] = [
    "MAX_MESSAGE_LENGTH",
    "ChatMessage",
    "ChatSession",
    "HealthStatus",
    "Token",
    "UserAccount",
]
